app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\Periodo;
use App\User;
use App\Area;

Route::group(['middleware' => 'auth'],function(){
	Route::group(['middleware'=>'status'],function(){
		Route::get('/', 'HomeController@index');

		Route::group(['middleware'=>'sistema'],function(){
			Route::get('usuarios/listar', ['as' =>'usuarios.listar' , 'uses' => 'UsuariosController@listar']);
			Route::resource('usuarios', 'UsuariosController');
			Route::get('roles/listar', ['as' =>'roles.listar' , 'uses' => 'RolesController@listar']);
			Route::resource('roles', 'RolesController');	
		});

		Route::group(['middleware'=>'admin'],function(){
			Route::get('/areas', function () {
				$li='areas';
				return view('dashboard.area.index')->with('li',$li);
			});	

			Route::put('administracion/cerrar_eva/{colaborador}', ['as' =>'administracion.cerrar_eva' , 'uses' => 'AdministracionController@cerrar_eva']);
			Route::get('administracion/cerrar_eva/{colaborador}', ['as' =>'administracion.cierre_vista' , 'uses' => 'AdministracionController@cierre_vista']);
			Route::put('administracion/evaluar/{colaborador}', ['as' =>'administracion.evaluar' , 'uses' => 'AdministracionController@evaluar']);
			Route::get('administracion/evaluar/{colaborador}', ['as' =>'administracion.evaluar_vista' , 'uses' => 'AdministracionController@evaluar_vista']);
			Route::put('administracion/inicio/{colaborador}', ['as' =>'administracion.inicio' , 'uses' => 'AdministracionController@inicio']);
			Route::get('administracion/evaluacion/{colaborador}', ['as' =>'administracion.evaluacion' , 'uses' => 'AdministracionController@evaluacion']);

			Route::get('trabajadores/listar', ['as' =>'trabajadores.listar' , 'uses' => 'TrabajadoresController@listar']);
			Route::resource('trabajadores', 'TrabajadoresController');
			
			Route::put('items/aprobar', ['as' =>'items.aprobar' , 'uses' => 'ItemsController@aprobar']);
			Route::put('items/rechazar', ['as' =>'items.rechazar' , 'uses' => 'ItemsController@rechazar']);
			Route::get('items/listar/{option?}', ['as' =>'items.listar' , 'uses' => 'ItemsController@listar']);
			Route::resource('items', 'ItemsController');

			Route::get('actividades/listar', ['as' =>'actividades.listar' , 'uses' => 'ActividadesController@listar']);
			Route::get('actividades/{cargo_id}/por_cargo', ['as' =>'actividades.por_cargo' , 'uses' => 'ActividadesController@por_cargo']);
			Route::resource('actividades', 'ActividadesController');

			Route::get('cargos/por_area/{area_id}', ['as' =>'CargosController.por_area' , 'uses' => 'CargosController@por_area']);
			Route::get('cargos/opciones', 'CargosController@opciones');
			Route::get('cargos/listar', ['as' =>'cargos.listar' , 'uses' => 'CargosController@listar']);
			Route::resource('cargos', 'CargosController');

			Route::get('periodos/historial', ['as' =>'periodos.listar' , 'uses' => 'PeriodosController@listar']);
			Route::get('periodos/listar', ['as' =>'periodos.listar' , 'uses' => 'PeriodosController@listar']);
			Route::resource('periodos', 'PeriodosController');

			Route::get('iniciativas/listar', ['as' =>'iniciativas.listar' , 'uses' => 'IniciativasController@listar']);
			Route::resource('iniciativas', 'IniciativasController');

			Route::get('zonas/opciones', 'ZonasController@opciones');
			Route::get('zonas/listar', ['as' =>'zonas.listar' , 'uses' => 'ZonasController@listar']);
			Route::resource('zonas', 'ZonasController');

			Route::get('departamentos/lideres', 'DepartamentosController@lideres');
			Route::get('departamentos/por_cargo/{cargo_id}', ['as' =>'por_cargo.por_cargo' , 'uses' => 'DepartamentosController@por_cargo']);
			Route::get('departamentos/opciones', 'DepartamentosController@opciones');
			Route::get('departamentos/padres', 'DepartamentosController@padres');
			Route::get('departamentos/listar', ['as' =>'departamentos.listar' , 'uses' => 'DepartamentosController@listar']);
			Route::resource('departamentos', 'DepartamentosController');

			Route::get('/configuracion-trimestre', function () {
				$li='config_trimestre';
            	$periodo = Periodo::all()->last();
				return view('dashboard.configuracion.index')->with('li',$li)->with('periodo',$periodo);
			});
			Route::get('/configuracion-anual', function () {
				$li='config_anual';
				return view('dashboard.configuracion.anual.index')->with('li',$li);
			});	

			Route::get('submodulos/listar/{option?}', ['as' =>'submodulos.listar' , 'uses' => 'SubmoduloController@listar']);
			Route::resource('submodulos', 'SubmoduloController');

			Route::get('eva/listar', ['as' =>'eva.listar' , 'uses' => 'EvaAnualController@listar']);
			Route::resource('eva', 'EvaAnualController');			
		});

		Route::group(['middleware'=>'lider'],function(){

			Route::put('lideres/evaluar/{colaborador}', ['as' =>'lideres.evaluar' , 'uses' => 'LiderController@evaluar']);
			Route::get('lideres/evaluar/{colaborador}', ['as' =>'lideres.evaluar_vista' , 'uses' => 'LiderController@evaluar_vista']);
			Route::put('lideres/inicio/{colaborador}', ['as' =>'lideres.inicio' , 'uses' => 'LiderController@inicio']);
			Route::get('lideres/evaluacion/{colaborador}', ['as' =>'lideres.evaluacion' , 'uses' => 'LiderController@evaluacion']);
			Route::get('lideres/colaboradores', ['as' =>'lideres.colaboradores' , 'uses' => 'LiderController@colaboradores']);
			Route::put('lideres/{categoria}/{area}', ['as' =>'lideres.actualizar' , 'uses' => 'LiderController@actualizar']);	
			Route::get('lideres/editar/{categoria}/{area}', ['as' =>'lideres.editar' , 'uses' => 'LiderController@editar']);
			Route::get('lideres/listar/{option?}', ['as' =>'lideres.listar' , 'uses' => 'LiderController@listar']);
			Route::resource('lideres', 'LiderController');
		});

		Route::group(['middleware'=>['colaborador']],function(){
			Route::get('/perfil/{id}', function ($id) {
		        $colaborador = User::findOrFail(Auth::user()->id);
		        $area = Area::findOrFail($colaborador->area_id);
		        if (Auth::user()->id!=1 && Auth::user()->id == $id && $colaborador->roles()->where('rol', 'Colaborador')->exists()) {
		            if (Auth::user()->roles()->whereIn('rol', ['Colaborador'])->exists()) {
		                $periodo = Periodo::all()->last();
		                $li='colaborador';            
		                return view('dashboard.colaboradores.show')->with('li',$li)->with('colaborador',$colaborador)->with('periodo',$periodo);
		            }
		            else{
			            Flash::error("RESTRINGIDO");            
			            return redirect('');        
		            }
		        }
		        else{
		            Flash::error("RESTRINGIDO");            
		            return redirect(''); 
		        };
			});
		});
	});
});

//para visualizar data de colaboradores
Route::get('compartida/stats_colaborador/{colaborador}', ['as' =>'compartida.stats_colaborador' , 'uses' => 'CompartidaController@stats_colaborador']);
Route::get('compartida/items/{colaborador}', ['as' =>'compartida.items_colaborador' , 'uses' => 'CompartidaController@items_colaborador']);

//info para los select
Route::get('compartida/{item}/indicador', ['as' =>'compartida.item_indicador' , 'uses' => 'CompartidaController@item_indicador']);
Route::get('compartida/{categoria}/items/{area}', ['as' =>'compartida.items' , 'uses' => 'CompartidaController@items']);


Route::get('/home', function () {
	$li='home';
	return view('home')->with('li',$li);
});

Route::auth();

app/Http/Controllers/UsuariosController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\UserRequest;
use Auth;
use App\User;
use App\Rol;

use Yajra\Datatables\Datatables;
use Laracasts\Flash\Flash;

use DB;
use Log;
use Exception;

class UsuariosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $li='usuarios';
        
        return view('dashboard.usuarios.index')->with('li',$li);
    }

    public function listar()
    {
        try {
            //$id=Auth::user()->id;
            //$usuario = User::where('id','!=', $id)->get();
            
            $usuario = User::whereDoesntHave('roles', function($q){ $q->where('rol', 'Master');})->get();
            $usuario->each(function($usuario){
                $usuario->roles;
                $usuario->permisos = '';
                foreach ($usuario->roles as $value) {
                    $usuario->permisos = $usuario->permisos.''.$value->rol.'</br>'; 
                }
                if ($usuario->status == 1) {
                    $usuario->status = 'Activo';
                } else {
                    $usuario->status = 'Inactivo';
                }
                return $usuario;
            });          
            return Datatables::of($usuario)->make(true);

        } catch (\Exception $e) {
            Log::error('Ha ocurrido un error en UsersController: '.$e->getMessage().', Linea: '.$e->getLine());
            return Datatables::of([])->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $li='usuarios';
        $roles=Rol::where('rol','!=','Master')->orderBy('rol')->get();
        return view('dashboard.usuarios.form')->with('li',$li)->with('roles',$roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
        [
            'cedula'=>'unique:users,cedula',
            'usuario'=>'required|unique:users,usuario',
            'email'=>'email',
            'nombre'=>'required|min:5|max:45',
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required|min:6',
            'roles' => 'required',
            'status' => 'required']);
        
        $usuario= new User($request->all());
        $usuario->password=bcrypt($request->password);
        $usuario->save();

        foreach ($request->roles as $rol){
            $usuario->roles()->attach($rol);                   
        }

        Flash::success("Se ha ingresado un nuevo usuario Nro. ". $usuario->id." ". $usuario->nombre."!!");
        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $usuario = User::findOrFail($id);
            return response()->json($usuario);
        } catch (\Exception $e) {
            Log::error('Ha ocurrido un error en UsersController: '.$e->getMessage().', Linea: '.$e->getLine());
            return response()->json([
                'message' => 'Ha ocurrido un error al tratar de obtener los datos.'
                ], 500);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ($id!=1) {        
            $li='usuarios';
            $usuario = User::findOrFail($id);
            $roles=Rol::where('rol','!=','Master')->orderBy('rol')->get();
            return view('dashboard.usuarios.form')->with('li',$li)->with('roles',$roles)->with('usuario',$usuario); 
        }
        else{
            Flash::error("RESTRINGIDO");            
            return redirect()->route('usuarios.index');           
        }     
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, 
        [
            'cedula'=>'required|unique:users,cedula,'.$id,
            'usuario'=>'required|unique:users,usuario,'.$id,
            'email'=>'required|email',
            'nombre'=>'required|min:5|max:45',
            'password' => 'min:6|confirmed',
            'password_confirmation' => 'min:6',
            'roles' => 'required',
            'status' => 'required']);
        
        $usuario = User::findOrFail($id);
        $pass_last = $usuario->password;
        $usuario->fill($request->all());

        if($request->password != null || !empty($request->password)){
            $usuario->password = bcrypt($request->password);
        }else{
            $usuario->password = $pass_last;
        }
        $usuario->roles()->detach();

        foreach ($request->roles as $rol){
            $usuario->roles()->attach($rol); 

        }
        $usuario->save();

        Flash::success("Se ha actualizado el usuario Nro. ". $usuario->id." ". $usuario->nombre."!!");
        return redirect()->route('usuarios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            $user = User::findOrFail($id);
            $user->roles()->sync([]);          
            $user->delete();
            DB::commit();
            return response()->json($id);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Ha ocurrido un error en ZonasController: '.$e->getMessage().', Linea: '.$e->getLine());
            return response()->json([
                'message' => 'Ha ocurrido un error al tratar de eliminar los datos.'
                ], 500);
        }
    }

}

resources/views/dashboard/usuarios/form.blade.php
@extends('layouts.main')

@section('title', 'Usuarios')

@section('css')

@endsection

@section('contenido')
<div class="row">
  <div class="col-md-offset-2 col-md-8">
      <div class=" box box-success ">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario para Usuarios</h3>
    </div>
    <div class="box-body" >

      @if(isset($usuario))
      {!! Form::open(['method' => 'PUT','route' => ['usuarios.update', $usuario->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!} 
      @else
      {!! Form::open(['method' => 'POST', 'route' => 'usuarios.store', 'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!} 
      @endif
        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">


        <div class="row form-group ">
            <div class=" col-md-6" {{ $errors->has('nombre') ? ' has-error' : '' }}">
                {!! Form::label('nombre', 'Nombre Completo:') !!}
                {!! Form::text('nombre', (isset($usuario)?$usuario->nombre:null), ['class' => 'form-control', 'required' => 'required', 'placeholder'=>'Angela Celeste Montilla Ruiz']) !!}
                <small class="text-danger">{{ $errors->first('nombre') }}</small>
            </div>
            <div class="col-md-6{{ $errors->has('cedula') ? ' has-error' : '' }}">
                {!! Form::label('cedula', 'Cédula de Identidad:') !!}
                {!! Form::text('cedula', (isset($usuario)?$usuario->cedula:null), ['class' => 'form-control numero', 'required' => 'required','onkeypress'=>'return soloNumeros(event)', 'dir'=>"rtl",  'placeholder'=>'23.533.432']) !!}
                <small class="text-danger">{{ $errors->first('cedula') }}</small>
            </div>
        </div>       
        <div class="row form-group">
          <div class=" col-md-6 {{ $errors->has('email') ? ' has-error' : '' }}">
              {!! Form::label('email', 'Email:') !!}
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope"  style="font-size: 12px"></i></span>
                {!! Form::email('email', (isset($usuario)?$usuario->email:null), ['class' => 'form-control', 'required' => 'required', 'placeholder' => 'ej: app@amazonastech.com.ve']) !!}
              </div>
              <small class="text-danger">{{ $errors->first('email') }}</small>
          </div>
          <div class=" col-md-6 {{ $errors->has('usuario') ? ' has-error' : '' }}">
              {!! Form::label('usuario', 'Nombre de Usuario:') !!}
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"  style="font-size: 12px"></i></span>
                {!! Form::text('usuario', (isset($usuario)?$usuario->usuario:null), ['id' => 'usuario','class'=>'form-control', 'required' => 'required','placeholder'=>'acmontilla','onkeypress'=>'return soloLetras(event)']) !!}
              </div>
              <small class="text-danger">{{ $errors->first('usuario') }}</small>
          </div>
        </div>       
        <div class="row form-group">
          <div class="col-md-6 {{ $errors->has('password') ? ' has-error' : '' }}">
              {!! Form::label('password', 'Contraseña:') !!}
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-unlock-alt" style="font-size: 17px"></i></span>
                {!! Form::password('password', ['id' => 'password','class' => 'form-control', 'placeholder'=>'********']) !!}
              </div>
              <small class="text-danger">{{ $errors->first('password') }}</small>
          </div>
          <div class="col-md-6 {{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
              {!! Form::label('password_confirmation', 'Confirmación de Contraseña:') !!}
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-unlock-alt" style="font-size: 17px"></i></span>
                {!! Form::password('password_confirmation', ['id' => 'password_confirmation','class' => 'form-control', 'placeholder'=>'********']) !!}
              </div>
              <small class="text-danger">{{ $errors->first('password_confirmation') }}</small>
          </div>
        </div>
        <div class="row form-group">
          <div class=" col-md-6 {{ $errors->has('status') ? ' has-error' : '' }}">
              {!! Form::label('status', 'Estatus de Usuario:') !!}
              {!! Form::select('status', ['1'=>'Activo','0'=>'Inactivo'], (isset($usuario)?$usuario->status:null), ['id' => 'status', 'class' => 'form-control', 'required' => 'required', 'placeholder'=>'Seleccione']) !!}
              <small class="text-danger">{{ $errors->first('status') }}</small>
          </div>
          <div class="col-md-6 ">
              {!! Form::label('roles', 'Roles de Usuario:') !!}
              <div class="checkbox{{ $errors->has('roles') ? ' has-error' : '' }}">
                  @foreach($roles as $rol)
                  <label for="roles">
                    {!! Form::checkbox('roles[]', $rol->id, ( isset($usuario) && in_array($rol->id, $usuario->roles->pluck('id')->toArray()) ?true:false), ['id' => 'roles']) !!} {{$rol->rol}}
                  </label></br>
                  @endforeach
              </div>
              <small class="text-danger">{{ $errors->first('roles') }}</small>
          </div>
        </div>                
    </div>  
    <div class="box-footer with-border">
      <a href="{{ url('usuarios') }}" class="btn btn-default btn-flat">Cancelar</a>
      {!! Form::submit('Guardar', ['class' => 'btn btn-success btn-flat pull-right']) !!}     
    </div>       
      {!! Form::close() !!}
  </div> 
  </div>
  
</div>
  
  
@endsection

@section('js')

<script type="text/javascript">

  $(".numero").on({
    "focus": function(event) {
      $(event.target).select();
    },
    "keyup": function(event) {
      $(event.target).val(function(index, value) {
        return value.replace(/\D/g, "")
          .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ".");
      });
    }
  });

  function soloNumeros(e){
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = "1234567890";
    especiales = "8-37-39-46";

    tecla_especial = false
    for(var i in especiales){
      if(key == especiales[i]){
        tecla_especial = true;
        break;
      }
    }

    if(letras.indexOf(tecla)==-1 && !tecla_especial){
      return false;
    }
  }

  function soloLetras(e){
    key = e.keyCode || e.which;
    tecla = String.fromCharCode(key).toLowerCase();
    letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
    especiales = "8-37-39-46";

    tecla_especial = false
    for(var i in especiales){
      if(key == especiales[i]){
        tecla_especial = true;
        break;
      }
    }

    if(letras.indexOf(tecla)==-1 && !tecla_especial){
      return false;
    }
  }

</script>

@endsection

resources/views/dashboard/usuarios/index.blade.php
@extends('layouts.main')

@section('title', 'Usuarios')

@section('css')

<!-- DataTables -->  
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">
<!-- sweealert -->
<link rel="stylesheet" type="text/css" href="{{asset('public/plugins/sweealert/sweetalert2.min.css')}}">

@endsection
@section('titulo_modulo', "Módulo de Usuarios")

@section('contenido')
<input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
  
<div class="row" >
  <div class="col-md-12">
    <!-- Custom Tabs -->
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab"><i class="fa fa-fw fa-users"></i> <b>Usuarios</b></a></li>
        <li><a href="#tab_2" data-toggle="tab"><i class="fa fa-fw fa-black-tie"></i> <b>Roles</b></a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
          <div style="padding-bottom: 15px">
            <a class="btn btn-default btn-flat btn-xs " href="{{route('usuarios.create')}}"><span class="text-success"><i class="fa fa-plus"></i></span>Agregar</a>
            <a href='javascript:void(0)' class="btn btn-default btn-flat btn-xs pull-right"  id="actualizar-user"><i class="fa fa-repeat"></i> Actualizar</a>
          </div>
          <table class="table table-bordered table-hover table-striped" id="tabla-usuarios" width="100%" >
            <thead style="">
              <tr>
                <th>Cédula</th>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Usuario</th>
                <th>Status</th>
                <th>Permisos</th>
                <th></th>
              </tr>
            </thead>
          </table> 
        </div>
        <!-- /.tab-pane -->
        <div class="tab-pane" id="tab_2">
          <table class="table table-bordered table-hover table-striped" id="tabla-roles" width="100%" >
            <thead style="">
              <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descripción</th>
              </tr>
            </thead>
          </table>   
        </div>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
    </div>
    <!-- nav-tabs-custom -->
  </div>
</div>
@include('dashboard.usuarios.rol')
  
@endsection

@section('js')

<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>

<!-- sweealert -->
<script type="text/javascript" src="{{asset('public/plugins/sweealert/promise.min.js')}}"></script>
<script type="text/javascript" src="{{asset('public/plugins/sweealert/sweetalert2.min.js')}}"></script>

<script src="{{asset('public/js/user.js')}}"></script>
<script type="text/javascript">

  $(document).ready(function() {
      $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
          // var target = $(e.target).attr("href"); // activated tab
          // alert (target);
          $($.fn.dataTable.tables( true ) ).css('width', '100%');
          $($.fn.dataTable.tables( true ) ).DataTable().columns.adjust().draw();
      } ); 
  }); 
  
  function starLoad(btn){
    $(btn).button('loading');
    $('.load-ajax').addClass('overlay');
    $('.load-ajax').html('<i class="fa fa-refresh fa-spin"></i>');
  } 

  function endLoad(btn){
    $(btn).button('reset');
    $('.load-ajax').removeClass('overlay');
    $('.load-ajax').fadeIn(1000).html("");
  } 

  $.fn.dataTable.ext.errMode = 'throw';
  
  var toolbar='<div class="pull-right">'+
                '{!! Form::text('rol', null, ['id'=>'rol', 'class' => 'form-control input-sm', 'placeholder'=>'Buscar nombre']) !!}'+
                '{!! Form::text('descripcion', null, ['id'=>'descripcion', 'class' => 'form-control input-sm', 'placeholder'=>'Buscar descripcion']) !!}'+
                '<a href="javascript:void(0)" class="btn btn-info btn-flat btn-sm"  id="buscar" title="Actualizar"><i class="fa fa-search"></i></a>'+
                '<button type="button" class="btn btn-success btn-flat btn-sm" data-toggle="modal" data-target="#modal-roles">'+
                '<i class="fa fa-plus"></i></button>'+
                '<a href="javascript:void(0)" class="btn btn-default btn-flat btn-sm"  id="actualizar-roles" title="Actualizar"><i class="fa fa-repeat"></i></a>'+
              '</div>';

</script>
<script src="{{asset('public/js/rol.js')}}"></script>

@endsection

resources/views/dashboard/usuarios/rol.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-roles" data-keyboard="false" data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content box">
      <div class="modal-header text-center">
        {!! Form::open(['id'=>'form-rol']) !!}
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Formulario para Roles</h4>
      </div>
      <div class="modal-body">
        {!! Form::hidden('token', csrf_token(), ['id'=>'token']) !!}
        {!! Form::hidden('rol_id', null, ['id'=>'rol_id']) !!}
        <div class="form-group" id="field-nombre-rol">
          {!! Form::label('rol_nombre', 'Nombre:') !!}
          {!! Form::text('rol_nombre', null, ['id' => 'rol_nombre','class' => 'form-control col-sm-4', 'required' => 'required']) !!}
          <span><strong class="text-danger msj-error"></strong></span>
        </div>
        </br></br>  
        <div class="form-group" id="field-descripcion-rol">
          {!! Form::label('rol_descripcion', 'Descripción:') !!}
          {!! Form::textarea('rol_descripcion', null, ['id' => 'rol_descripcion','class' => 'form-control col-sm-4', 'required' => 'required', 'rows'=>3]) !!}
          <span><strong class="text-danger msj-error"></strong></span>
        </div>
        </br>  
        </br>
        </br> 
      </div>
      <div class="modal-footer">
        <div >
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
          <button type="button" id="guardar-rol" class="btn btn-success pull-right" data-loading-text="Guardando..." autocomplete="off">Guardar</button>
        </div>      
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>