app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\Periodo;
use App\User;
use App\Area;

Route::group(['middleware' => 'auth'],function(){
	Route::group(['middleware'=>'status'],function(){
		Route::get('/', 'HomeController@index');

		Route::group(['middleware'=>'sistema'],function(){
			Route::get('usuarios/listar', ['as' =>'usuarios.listar' , 'uses' => 'UsuariosController@listar']);
			Route::resource('usuarios', 'UsuariosController');
			Route::get('roles/listar', ['as' =>'roles.listar' , 'uses' => 'RolesController@listar']);
			Route::resource('roles', 'RolesController');	
		});

		Route::group(['middleware'=>'admin'],function(){
			Route::get('/areas', function () {
				$li='areas';
				return view('dashboard.area.index')->with('li',$li);
			});	

			Route::put('administracion/cerrar_eva/{colaborador}', ['as' =>'administracion.cerrar_eva' , 'uses' => 'AdministracionController@cerrar_eva']);
			Route::get('administracion/cerrar_eva/{colaborador}', ['as' =>'administracion.cierre_vista' , 'uses' => 'AdministracionController@cierre_vista']);
			Route::put('administracion/evaluar/{colaborador}', ['as' =>'administracion.evaluar' , 'uses' => 'AdministracionController@evaluar']);
			Route::get('administracion/evaluar/{colaborador}', ['as' =>'administracion.evaluar_vista' , 'uses' => 'AdministracionController@evaluar_vista']);
			Route::put('administracion/inicio/{colaborador}', ['as' =>'administracion.inicio' , 'uses' => 'AdministracionController@inicio']);
			Route::get('administracion/evaluacion/{colaborador}', ['as' =>'administracion.evaluacion' , 'uses' => 'AdministracionController@evaluacion']);

			Route::get('trabajadores/listar', ['as' =>'trabajadores.listar' , 'uses' => 'TrabajadoresController@listar']);
			Route::resource('trabajadores', 'TrabajadoresController');
			
			Route::put('items/aprobar', ['as' =>'items.aprobar' , 'uses' => 'ItemsController@aprobar']);
			Route::put('items/rechazar', ['as' =>'items.rechazar' , 'uses' => 'ItemsController@rechazar']);
			Route::get('items/listar/{option?}', ['as' =>'items.listar' , 'uses' => 'ItemsController@listar']);
			Route::resource('items', 'ItemsController');

			Route::get('actividades/listar', ['as' =>'actividades.listar' , 'uses' => 'ActividadesController@listar']);
			Route::get('actividades/{cargo_id}/por_cargo', ['as' =>'actividades.por_cargo' , 'uses' => 'ActividadesController@por_cargo']);
			Route::resource('actividades', 'ActividadesController');

			Route::get('cargos/por_area/{area_id}', ['as' =>'CargosController.por_area' , 'uses' => 'CargosController@por_area']);
			Route::get('cargos/opciones', 'CargosController@opciones');
			Route::get('cargos/listar', ['as' =>'cargos.listar' , 'uses' => 'CargosController@listar']);
			Route::resource('cargos', 'CargosController');

			Route::get('periodos/historial', ['as' =>'periodos.listar' , 'uses' => 'PeriodosController@listar']);
			Route::get('periodos/listar', ['as' =>'periodos.listar' , 'uses' => 'PeriodosController@listar']);
			Route::resource('periodos', 'PeriodosController');

			Route::get('iniciativas/listar', ['as' =>'iniciativas.listar' , 'uses' => 'IniciativasController@listar']);
			Route::resource('iniciativas', 'IniciativasController');

			Route::get('zonas/opciones', 'ZonasController@opciones');
			Route::get('zonas/listar', ['as' =>'zonas.listar' , 'uses' => 'ZonasController@listar']);
			Route::resource('zonas', 'ZonasController');

			Route::get('departamentos/lideres', 'DepartamentosController@lideres');
			Route::get('departamentos/por_cargo/{cargo_id}', ['as' =>'por_cargo.por_cargo' , 'uses' => 'DepartamentosController@por_cargo']);
			Route::get('departamentos/opciones', 'DepartamentosController@opciones');
			Route::get('departamentos/padres', 'DepartamentosController@padres');
			Route::get('departamentos/listar', ['as' =>'departamentos.listar' , 'uses' => 'DepartamentosController@listar']);
			Route::resource('departamentos', 'DepartamentosController');

			Route::get('/configuracion-trimestre', function () {
				$li='config_trimestre';
            	$periodo = Periodo::all()->last();
				return view('dashboard.configuracion.index')->with('li',$li)->with('periodo',$periodo);
			});
			Route::get('/configuracion-anual', function () {
				$li='config_anual';
				return view('dashboard.configuracion.anual.index')->with('li',$li);
			});	

			Route::get('submodulos/listar/{option?}', ['as' =>'submodulos.listar' , 'uses' => 'SubmoduloController@listar']);
			Route::resource('submodulos', 'SubmoduloController');

			Route::get('eva/listar', ['as' =>'eva.listar' , 'uses' => 'EvaAnualController@listar']);
			Route::resource('eva', 'EvaAnualController');			
		});

		Route::group(['middleware'=>'lider'],function(){

			Route::put('lideres/evaluar/{colaborador}', ['as' =>'lideres.evaluar' , 'uses' => 'LiderController@evaluar']);
			Route::get('lideres/evaluar/{colaborador}', ['as' =>'lideres.evaluar_vista' , 'uses' => 'LiderController@evaluar_vista']);
			Route::put('lideres/inicio/{colaborador}', ['as' =>'lideres.inicio' , 'uses' => 'LiderController@inicio']);
			Route::get('lideres/evaluacion/{colaborador}', ['as' =>'lideres.evaluacion' , 'uses' => 'LiderController@evaluacion']);
			Route::get('lideres/colaboradores', ['as' =>'lideres.colaboradores' , 'uses' => 'LiderController@colaboradores']);
			Route::put('lideres/{categoria}/{area}', ['as' =>'lideres.actualizar' , 'uses' => 'LiderController@actualizar']);	
			Route::get('lideres/editar/{categoria}/{area}', ['as' =>'lideres.editar' , 'uses' => 'LiderController@editar']);
			Route::get('lideres/listar/{option?}', ['as' =>'lideres.listar' , 'uses' => 'LiderController@listar']);
			Route::resource('lideres', 'LiderController');
		});

		Route::group(['middleware'=>['colaborador']],function(){
			Route::get('/perfil/{id}', function ($id) {
		        $colaborador = User::findOrFail(Auth::user()->id);
		        $area = Area::findOrFail($colaborador->area_id);
		        if (Auth::user()->id!=1 && Auth::user()->id == $id && $colaborador->roles()->where('rol', 'Colaborador')->exists()) {
		            if (Auth::user()->roles()->whereIn('rol', ['Colaborador'])->exists()) {
		                $periodo = Periodo::all()->last();
		                $li='colaborador';            
		                return view('dashboard.colaboradores.show')->with('li',$li)->with('colaborador',$colaborador)->with('periodo',$periodo);
		            }
		            else{
			            Flash::error("RESTRINGIDO");            
			            return redirect('');        
		            }
		        }
		        else{
		            Flash::error("RESTRINGIDO");            
		            return redirect(''); 
		        };
			});
		});
	});
});

//para visualizar data de colaboradores
Route::get('compartida/stats_colaborador/{colaborador}', ['as' =>'compartida.stats_colaborador' , 'uses' => 'CompartidaController@stats_colaborador']);
Route::get('compartida/items/{colaborador}', ['as' =>'compartida.items_colaborador' , 'uses' => 'CompartidaController@items_colaborador']);

//info para los select
Route::get('compartida/{item}/indicador', ['as' =>'compartida.item_indicador' , 'uses' => 'CompartidaController@item_indicador']);
Route::get('compartida/{categoria}/items/{area}', ['as' =>'compartida.items' , 'uses' => 'CompartidaController@items']);


Route::get('/home', function () {
	$li='home';
	return view('home')->with('li',$li);
});

Route::auth();

resources/views/dashboard/configuracion/anual/index.blade.php
@extends('layouts.main')

@section('title', 'Módulo de Configuración de Evaluaciones')

@section('css')
  <!-- DataTables -->  
  <link rel="stylesheet" type="text/css" href="{{asset('public/plugins/datatables/dataTables.bootstrap.css')}}">
  <!-- sweealert -->
  <link rel="stylesheet" type="text/css" href="{{asset('public/plugins/sweealert/sweetalert2.min.css')}}">

@endsection

@section('titulo_modulo', "Módulo de Configuración de Evaluaciones")

@section('contenido')
<input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">

<div class="row" >
  <div class="col-md-12">
    <!-- Custom Tabs -->
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab"><i class="fa fa-fw fa-calendar"></i> <b>Configuración de Evaluaciones anuales</b></a></li>
        <li><a href="#tab_2" data-toggle="tab"><span class="glyphicon glyphicon-equalizer text-maroon"></span> <b>Items Generales</b></a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
          <div style="padding-bottom: 15px">
            <a class="btn btn-default btn-flat btn-sm" href="{{route('eva.create')}}"><span class="text-success"><i class="fa fa-plus"></i></span>Agregar</a>
            <a href='javascript:void(0)' class="btn btn-default btn-flat btn-sm pull-right"  id="actualizar-periodos" title="Actualizar"><i class="fa fa-repeat"></i></a>
          </div>
          <table class="table table-bordered table-hover table-striped" id="tabla-periodos" width="100%" >
            <thead style="">
              <tr>
                <th>Año</th>
                <th>Categorias</th>
                <th>Condición</th>
                <th>Acción</th>

              </tr>
            </thead>
          </table>
        </div>
        <!-- /.tab-pane -->
        <div class="tab-pane" id="tab_2">
          <div style="padding-bottom: 15px">
            <a class="btn btn-default btn-flat btn-sm" href="{{route('submodulos.create')}}"><span class="text-success"><i class="fa fa-plus"></i></span>Agregar</a>
            <a href='javascript:void(0)' class="btn btn-default btn-flat btn-sm pull-right"  id="actualizar-items" title="Actualizar"><i class="fa fa-repeat"></i></a>
          </div>
          <table class="table table-bordered table-hover table-striped" id="tabla-items" width="100%" >
            <thead style="">
              <tr>
                <th>Categoría</th>
                <th>Nombre</th>
                <th>Indicador</th>
                <th>Permiso</th>
                <th></th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Categoría</th>
                <th>Nombre</th>
                <th>Indicador</th>
                <th></th>
              </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.tab-pane -->
      </div>
      <!-- /.tab-content -->
    </div>
    <!-- nav-tabs-custom -->
  </div>
</div>

@endsection

@section('js')

<!-- DataTables -->
<script src="{{asset('public/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('public/plugins/datatables/dataTables.bootstrap.min.js')}}"></script>
<!-- sweealert -->
<script type="text/javascript" src="{{asset('public/plugins/sweealert/promise.min.js')}}"></script>
<script type="text/javascript" src="{{asset('public/plugins/sweealert/sweetalert2.min.js')}}"></script>

<script src="{{asset('public/js/validate.js')}}"></script>

<script type="text/javascript">
  $(document).ready(function() {
      $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
          // var target = $(e.target).attr("href"); // activated tab
          // alert (target);
          $($.fn.dataTable.tables( true ) ).css('width', '100%');
          $($.fn.dataTable.tables( true ) ).DataTable().columns.adjust().draw();
      } ); 
  }); 

  $.fn.dataTable.ext.errMode = 'throw';

</script>

<script src="{{asset('public/js/evaanual.js')}}"></script>


@endsection

resources/views/dashboard/configuracion/anual/itemform.blade.php
@extends('layouts.main')

@section('title', 'Configuracuón de Evaluación Trimestral')

@section('css')

@endsection

@section('contenido')
<div class="row">
  <div class="col-md-offset-2 col-md-8">
      <div class=" box box-success ">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario para Items de Evaluación Trimestral</h3>
    </div>
    <div class="box-body" >

    @if(isset($modulo))
      {!! Form::open(['method' => 'PUT','route' => ['submodulos.update', $modulo->id] ,'class' => 'form-horizontal']) !!}
    @else
      {!! Form::open(['method' => 'POST', 'route' => 'submodulos.store', 'class' => 'form-horizontal']) !!}
    @endif 
        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
        <div class="col-md-12 form-group">
          <div class="{{ $errors->has('modulo_id') ? ' has-error' : '' }}">
              {!! Form::label('modulo_id', '¿A cual módulo pertenecerán estos items?') !!}
              {!! Form::select('modulo_id', $opciones, (isset($modulo)?$modulo->id:null), ['id' => 'modulo_id', 'class' => 'form-control', 'required' => 'required', 'placeholder'=>'Seleccione']) !!}
              <small class="text-danger">{{ $errors->first('modulo_id') }}</small>
          </div>          
        </div>

        <table class="table table-bordered table-hover table-striped" id="tabla" width="100%" >
          <thead style="">
            <tr>
              <th>Items a Evaluar</th>
              <th>Indicadores</th>
              <th>Permisos</th>
              <th width="25px">
                @if (isset($modulo) == null || (isset($modulo) && $modulo->evaluacion->condicion =='Primer Corte'))
                  <a class="btn btn-success btn-xs btn-flat" id="add" title="Añadir fila"><i class="fa fa-plus"></i> </a> 
                @endif
              </th>
            </tr>
          </thead>
          <tbody>
            @if (isset($modulo))
              {!! Form::hidden('ids[]', 0) !!}
              @for($i = 0; $i < $modulo->submodulos->count(); $i++)
                <tr>
                  {!! Form::hidden('ids[]', $modulo->submodulos[$i]->id) !!}
                  <td>
                    {!! Form::textarea('submodulo[]', $modulo->submodulos[$i]->nombre, ['id'=>'submodulo[]','class' => 'form-control', 'required' => 'required', 'placeholder'=>'Item a Evaluar', 'minlength'=>5, 'rows'=>'1']) !!}
                  </td> 
                  <td>
                    {!! Form::textarea('indi[]', $modulo->submodulos[$i]->indicador, ['id' => 'indi[]','class' => 'form-control', 'required' => 'required', 'placeholder'=>'Indicador', 'rows'=>1]) !!}
                  </td> 
                  <td>
                    {!! Form::select('per[]', [0=>'Administración',1=>'Lideres'], $modulo->submodulos[$i]->permiso, ['id' => 'per[]', 'class' => 'form-control permisos', 'required' => 'required']) !!}                    
                  </td>
                  <td>
                    <a class='btn btn-danger btn-xs btn-flat del' id="del[]" title='Eliminar fila'><i class='fa fa-minus'></i></a>  
                  </td> 
                </tr>                
              @endfor
            @else
              <tr>
                <td>{!! Form::textarea('nombre[]', null, ['id'=>'nombre[]','class' => 'form-control', 'required' => 'required', 'placeholder'=>'Item a Evaluar', 'minlength'=>5, 'rows'=>'1']) !!}</td> 
                <td>
                  {!! Form::textarea('indicador[]', null, ['id' => 'indicador[]','class' => 'form-control', 'required' => 'required', 'placeholder'=>'Indicador', 'rows'=>1]) !!}
                </td>
                <td><select id='permiso[]' class='form-control permisos' required='required' name='permiso[]'><option selected='selected' value=''>Seleccione</option><option value='0'>Administraci&oacute;n</option><option value='1'>Lideres</option></select></td>
                <td></td> 
              </tr>           
            @endif             
          </tbody>
        </table>              
    </div>  
    <div class="box-footer with-border">
      <a href="{{ url('configuracion-anual') }}" class="btn btn-default btn-flat">Cancelar</a>
      {!! Form::submit('Guardar', ['id' => 'guardar', 'class' => 'btn btn-success btn-flat pull-right']) !!}     
    </div>       
      {!! Form::close() !!}
  </div> 
  </div>
  
</div>
  
  
@endsection

@section('js')

<script type="text/javascript">
  $(document).ready(function(){
    @if (isset($modulo))
      $("#modulo_id").prop('disabled',true);
    @endif
  });
  /**
   * Funcion para añadir una nueva fila en la tabla
   */
  $("#add").click(function(){
    var nuevaFila="<tr>"+
      '<td>'+
      '{!! Form::textarea('nombre[]', null, ['id'=>'nombre[]','class' => 'form-control', 'required' => 'required', 'placeholder'=>'Item a Evaluar', 'minlength'=>5, 'rows'=>'1'])!!}'+
      '</td> '+
      '<td>'+
      '{!! Form::textarea('indicador[]', null, ['id' => 'indicador[]','class' => 'form-control', 'required' => 'required', 'placeholder'=>'Indicador', 'rows'=>1]) !!}'+
      '</td> '+
      "<td><select id='permiso[]' class='form-control permisos' required='required' name='permiso[]'><option selected='selected' value=''>Seleccione</option><option value='0'>Administraci&oacute;n</option><option value='1'>Lideres</option></select></td> "+
      '<td><a class="btn btn-danger btn-xs btn-flat del" title="Eliminar fila"><i class="fa fa-minus"></i></a></td> '+
    '</tr>';
    $("#tabla tbody").append(nuevaFila);

  });

  // evento para eliminar la fila
  $("#tabla").on("click", ".del", function(){
    var num = $('.clonedInput').length;

    if (num-1 == 1)
      {
        $('.del').attr('disabled','disabled');
      }
    else{
      $(this).parents("tr").remove();
    }   
  });

</script>

@endsection

resources/views/dashboard/configuracion/anual/periodoform.blade.php
@extends('layouts.main')

@section('title', 'Configuracuón de Evaluación Anual')

@section('css')

@endsection

@section('contenido')
<div class="row">
  <div class="col-md-offset-2 col-md-8">
      <div class=" box box-success ">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario para Períodos de Evaluación Anual</h3>
    </div>
    <div class="box-body" >

      @if(isset($periodo))
      {!! Form::open(['method' => 'PUT','route' => ['eva.update', $periodo->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!}
      {!! Form::hidden('id', $periodo->id) !!}  
      @else
      {!! Form::open(['method' => 'POST', 'route' => 'eva.store', 'class' => 'form-horizontal']) !!} 
      @endif
        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
        <div class="row form-group">
          <div class="col-md-6"> 
            <div class="{{ $errors->has('anio') ? ' has-error' : '' }}">
                {!! Form::label('anio', 'Año:') !!}
                {!! Form::text('anio', (isset($periodo)?$periodo->anio:$anio), ['class' => 'form-control', 'required' => 'required', 'readonly'=>'true']) !!}
                <small class="text-danger">{{ $errors->first('anio') }}</small>
            </div>
          </div>
          <div class="col-md-6 ">
            <div class="{{ $errors->has('condicion') ? ' has-error' : '' }}">
                {!! Form::label('condicion', 'Condición:') !!}
                @if(isset($periodo)==null || (isset($periodo) && $periodo->condicion == 'Iniciando'))
                {!! Form::select('condicion', ['Iniciando'=>'Iniciando','Primer Corte'=>'Primer Corte','Segundo Corte'=>'Segundo Corte','Tercer Corte'=>'Tercer Corte','Cuarto Corte'=>'Cuarto Corte','Cerrado'=>'Cerrado'], (isset($periodo)?$periodo->condicion:'Iniciando'), ['id' => 'condicion', 'class' => 'form-control', 'required' => 'required']) !!}
                @elseif(isset($periodo) && $periodo->condicion != 'Iniciando')
                {!! Form::select('condicion', ['Primer Corte'=>'Primer Corte','Segundo Corte'=>'Segundo Corte','Tercer Corte'=>'Tercer Corte','Cuarto Corte'=>'Cuarto Corte','Cerrado'=>'Cerrado'], (isset($periodo)?$periodo->condicion:'Iniciando'), ['id' => 'condicion', 'class' => 'form-control', 'required' => 'required']) !!}
                @endif
                <small class="text-danger">{{ $errors->first('condicion') }}</small>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          {!! Form::label('total', 'Porcentaje Total:') !!}
          <br />
          <div class="progress active">
            <div id="total" class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" >                  
            </div>
          </div>
        </div>
        <table class="table table-bordered table-hover table-striped" id="tabla" width="100%" >
          <thead style="">
            <tr>
              <th>Categorías a Evaluar</th>
              <th width="25px">Porcentaje</th>
              <th width="25px">
                @if (isset($periodo)==null ||(isset($periodo) && $periodo->condicion=='Iniciando'))
                  <a class="btn btn-success btn-xs btn-flat" id="add" title="Añadir fila"><i class="fa fa-plus"></i> </a> 
                @endif
              </th>
            </tr>
          </thead>
          <tbody>
            @if (isset($periodo))
              {!! Form::hidden('ids[]', 0) !!}
              @for($i = 0; $i < $periodo->modulos->count(); $i++)
                <tr>
                  {!! Form::hidden('ids[]', $periodo->modulos[$i]->id) !!}
                  <td>
                    <input type='text' name='cat[]' id='cat[]' class='form-control modulos' maxlength='200' minlength='5' required='true' placeholder='Categoría' value="{{$periodo->modulos[$i]->nombre}}">
                  </td> 
                  <td>
                    <input type='text' name='por[]' id='por[]' class='form-control columnas new' min='1' max='100' required='true' onkeypress='return soloNumeros(event)' value="{{$periodo->modulos[$i]->porcentaje}}">
                  </td> 
                  <td>
                    @if ($periodo->condicion=='Iniciando')
                      <a class='btn btn-danger btn-xs btn-flat del' id="del[]" title='Eliminar fila'><i class='fa fa-minus'></i></a>
                    @endif  
                  </td> 
                </tr>                
              @endfor
            @else
              <tr>
                <td><input type='text' name='nombre[]' id='nombre[]' class='form-control modulos' maxlength='200' minlength='5' required='true' placeholder='Categoría'></td> 
                <td><input type='text' name='porcentaje[]' id='porcentaje[]' class='form-control columnas new' min='1' max='100' required='true' onkeypress='return soloNumeros(event)'></td> 
                <td></td> 
              </tr>             
            @endif
          </tbody>
        </table>
        <div class="col-sm-offset-6">
          <span class="text-danger">No podra guardar si el total de porcentaje no es igual a 100%</span>
        </div>              
    </div>  
    <div class="box-footer with-border">
      <a href="{{ url('configuracion-anual') }}" class="btn btn-default btn-flat">Cancelar</a>
      {!! Form::submit('Guardar', ['id' => 'guardar', 'class' => 'btn btn-success btn-flat pull-right', 'disabled'=>'true']) !!}     
    </div>       
      {!! Form::close() !!}
  </div> 
  </div>
  
</div>
  
  
@endsection

@section('js')

<script type="text/javascript">
  $(document).ready(function(){
    /**
    @if (isset($periodo) && $periodo->condicion != 'Iniciando')
      $(".modulos").each(function() {$(this).prop('disabled',true);});
      $(".columnas").each(function() {$(this).prop('disabled',true);});
      $(".permisos").each(function() {$(this).prop('disabled',true);});
      $(".del").each(function() {$(this).prop('disabled',true);});
    @endif
    */
    Calculate();
  });

  /**
   * Funcion para añadir una nueva fila en la tabla
   */
  $("#add").click(function(){
    var nuevaFila="<tr>"+
      "<td><input type='text' name='nombre[]' id='nombre[]' class='form-control modulos' maxlength='200' minlength='5' required='true' placeholder='Categoría'></td> "+
      "<td><input type='text' name='porcentaje[]' id='porcentaje[]' class='form-control columnas new' min='1' max='100' required='true' onkeypress='return soloNumeros(event)'></td> "+
      "<td><a class='btn btn-danger btn-xs btn-flat del' title='Eliminar fila'><i class='fa fa-minus'></i></a></td> "+
    "</tr>";
    $("#tabla tbody").append(nuevaFila);
    $('.new').keyup(function() {
      Calculate();
    });
  });

  // evento para eliminar la fila
  $("#tabla").on("click", ".del", function(){
    $(this).parents("tr").remove();
    Calculate();
  });

  //cada vez que el usuario orpime una tacla
  $('.columnas').keyup(function() {
    Calculate();
  });

function Calculate(){
  var total = 0;
  //recorremos los input para que haga la suma
  $(".columnas").each(
    function() {
      if (Number($(this).val())) {
        total = total + Number($(this).val());
      }
    });
  var elem = document.getElementById("total");   
  var width=total;
  elem.style.width = width + '%';
  $( "#total" ).text( width+"%");

  if (total == 100) {
    $("#total").removeClass("progress-bar-danger").addClass("progress-bar-success");
    $('#guardar').prop('disabled',false)
  }
  else {
    $("#total").removeClass("progress-bar-success").addClass("progress-bar-danger");
    $('#guardar').prop('disabled',true)      
  }
}

function soloNumeros(e){
  key = e.keyCode || e.which;
  tecla = String.fromCharCode(key).toLowerCase();
  letras = "1234567890";
  especiales = "8-37-39-46";

  tecla_especial = false
  for(var i in especiales){
    if(key == especiales[i]){
      tecla_especial = true;
      break;
    }
  }

  if(letras.indexOf(tecla)==-1 && !tecla_especial){
    return false;
  }
}
</script>

@endsection