app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\Periodo;
use App\User;
use App\Area;

Route::group(['middleware' => 'auth'],function(){
	Route::group(['middleware'=>'status'],function(){
		Route::get('/', 'HomeController@index');

		Route::group(['middleware'=>'sistema'],function(){
			Route::get('usuarios/listar', ['as' =>'usuarios.listar' , 'uses' => 'UsuariosController@listar']);
			Route::resource('usuarios', 'UsuariosController');
			Route::get('roles/listar', ['as' =>'roles.listar' , 'uses' => 'RolesController@listar']);
			Route::resource('roles', 'RolesController');	
		});

		Route::group(['middleware'=>'admin'],function(){
			Route::get('/areas', function () {
				$li='areas';
				return view('dashboard.area.index')->with('li',$li);
			});	

			Route::put('administracion/cerrar_eva/{colaborador}', ['as' =>'administracion.cerrar_eva' , 'uses' => 'AdministracionController@cerrar_eva']);
			Route::get('administracion/cerrar_eva/{colaborador}', ['as' =>'administracion.cierre_vista' , 'uses' => 'AdministracionController@cierre_vista']);
			Route::put('administracion/evaluar/{colaborador}', ['as' =>'administracion.evaluar' , 'uses' => 'AdministracionController@evaluar']);
			Route::get('administracion/evaluar/{colaborador}', ['as' =>'administracion.evaluar_vista' , 'uses' => 'AdministracionController@evaluar_vista']);
			Route::put('administracion/inicio/{colaborador}', ['as' =>'administracion.inicio' , 'uses' => 'AdministracionController@inicio']);
			Route::get('administracion/evaluacion/{colaborador}', ['as' =>'administracion.evaluacion' , 'uses' => 'AdministracionController@evaluacion']);

			Route::get('trabajadores/listar', ['as' =>'trabajadores.listar' , 'uses' => 'TrabajadoresController@listar']);
			Route::resource('trabajadores', 'TrabajadoresController');
			
			Route::put('items/aprobar', ['as' =>'items.aprobar' , 'uses' => 'ItemsController@aprobar']);
			Route::put('items/rechazar', ['as' =>'items.rechazar' , 'uses' => 'ItemsController@rechazar']);
			Route::get('items/listar/{option?}', ['as' =>'items.listar' , 'uses' => 'ItemsController@listar']);
			Route::resource('items', 'ItemsController');

			Route::get('actividades/listar', ['as' =>'actividades.listar' , 'uses' => 'ActividadesController@listar']);
			Route::get('actividades/{cargo_id}/por_cargo', ['as' =>'actividades.por_cargo' , 'uses' => 'ActividadesController@por_cargo']);
			Route::resource('actividades', 'ActividadesController');

			Route::get('cargos/por_area/{area_id}', ['as' =>'CargosController.por_area' , 'uses' => 'CargosController@por_area']);
			Route::get('cargos/opciones', 'CargosController@opciones');
			Route::get('cargos/listar', ['as' =>'cargos.listar' , 'uses' => 'CargosController@listar']);
			Route::resource('cargos', 'CargosController');

			Route::get('periodos/historial', ['as' =>'periodos.listar' , 'uses' => 'PeriodosController@listar']);
			Route::get('periodos/listar', ['as' =>'periodos.listar' , 'uses' => 'PeriodosController@listar']);
			Route::resource('periodos', 'PeriodosController');

			Route::get('iniciativas/listar', ['as' =>'iniciativas.listar' , 'uses' => 'IniciativasController@listar']);
			Route::resource('iniciativas', 'IniciativasController');

			Route::get('zonas/opciones', 'ZonasController@opciones');
			Route::get('zonas/listar', ['as' =>'zonas.listar' , 'uses' => 'ZonasController@listar']);
			Route::resource('zonas', 'ZonasController');

			Route::get('departamentos/lideres', 'DepartamentosController@lideres');
			Route::get('departamentos/por_cargo/{cargo_id}', ['as' =>'por_cargo.por_cargo' , 'uses' => 'DepartamentosController@por_cargo']);
			Route::get('departamentos/opciones', 'DepartamentosController@opciones');
			Route::get('departamentos/padres', 'DepartamentosController@padres');
			Route::get('departamentos/listar', ['as' =>'departamentos.listar' , 'uses' => 'DepartamentosController@listar']);
			Route::resource('departamentos', 'DepartamentosController');

			Route::get('/configuracion-trimestre', function () {
				$li='config_trimestre';
            	$periodo = Periodo::all()->last();
				return view('dashboard.configuracion.index')->with('li',$li)->with('periodo',$periodo);
			});
			Route::get('/configuracion-anual', function () {
				$li='config_anual';
				return view('dashboard.configuracion.anual.index')->with('li',$li);
			});	

			Route::get('submodulos/listar/{option?}', ['as' =>'submodulos.listar' , 'uses' => 'SubmoduloController@listar']);
			Route::resource('submodulos', 'SubmoduloController');

			Route::get('eva/listar', ['as' =>'eva.listar' , 'uses' => 'EvaAnualController@listar']);
			Route::resource('eva', 'EvaAnualController');			
		});

		Route::group(['middleware'=>'lider'],function(){

			Route::put('lideres/evaluar/{colaborador}', ['as' =>'lideres.evaluar' , 'uses' => 'LiderController@evaluar']);
			Route::get('lideres/evaluar/{colaborador}', ['as' =>'lideres.evaluar_vista' , 'uses' => 'LiderController@evaluar_vista']);
			Route::put('lideres/inicio/{colaborador}', ['as' =>'lideres.inicio' , 'uses' => 'LiderController@inicio']);
			Route::get('lideres/evaluacion/{colaborador}', ['as' =>'lideres.evaluacion' , 'uses' => 'LiderController@evaluacion']);
			Route::get('lideres/colaboradores', ['as' =>'lideres.colaboradores' , 'uses' => 'LiderController@colaboradores']);
			Route::put('lideres/{categoria}/{area}', ['as' =>'lideres.actualizar' , 'uses' => 'LiderController@actualizar']);	
			Route::get('lideres/editar/{categoria}/{area}', ['as' =>'lideres.editar' , 'uses' => 'LiderController@editar']);
			Route::get('lideres/listar/{option?}', ['as' =>'lideres.listar' , 'uses' => 'LiderController@listar']);
			Route::resource('lideres', 'LiderController');
		});

		Route::group(['middleware'=>['colaborador']],function(){
			Route::get('/perfil/{id}', function ($id) {
		        $colaborador = User::findOrFail(Auth::user()->id);
		        $area = Area::findOrFail($colaborador->area_id);
		        if (Auth::user()->id!=1 && Auth::user()->id == $id && $colaborador->roles()->where('rol', 'Colaborador')->exists()) {
		            if (Auth::user()->roles()->whereIn('rol', ['Colaborador'])->exists()) {
		                $periodo = Periodo::all()->last();
		                $li='colaborador';            
		                return view('dashboard.colaboradores.show')->with('li',$li)->with('colaborador',$colaborador)->with('periodo',$periodo);
		            }
		            else{
			            Flash::error("RESTRINGIDO");            
			            return redirect('');        
		            }
		        }
		        else{
		            Flash::error("RESTRINGIDO");            
		            return redirect(''); 
		        };
			});
		});
	});
});

//para visualizar data de colaboradores
Route::get('compartida/stats_colaborador/{colaborador}', ['as' =>'compartida.stats_colaborador' , 'uses' => 'CompartidaController@stats_colaborador']);
Route::get('compartida/items/{colaborador}', ['as' =>'compartida.items_colaborador' , 'uses' => 'CompartidaController@items_colaborador']);

//info para los select
Route::get('compartida/{item}/indicador', ['as' =>'compartida.item_indicador' , 'uses' => 'CompartidaController@item_indicador']);
Route::get('compartida/{categoria}/items/{area}', ['as' =>'compartida.items' , 'uses' => 'CompartidaController@items']);


Route::get('/home', function () {
	$li='home';
	return view('home')->with('li',$li);
});

Route::auth();

resources/views/dashboard/evaluaciones/anual/cierre.blade.php
@extends('layouts.main')

@section('title', 'Evaluación|'.$period.'|'.$colaborador->nombre)

@section('css')

@endsection

@section('titulo_modulo', 'Evaluación|'.$period.'|'.$colaborador->nombre)

@section('contenido')
<div class="row">
  <div class=" col-md-12">
    <div class=" box box-success ">
      <div class="box-header with-border">
          <h3 class="box-title">Formulario para Evaluaciones</h3>
      </div>
      <div class="box-body" >
        {!! Form::open(['method' => 'PUT','route' => ['administracion.cerrar_eva', $colaborador->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!}

        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
        <div class="row col-md-12">
          <div class="col-sm-4">
            <dl>
              <dt>Nombre</dt>
                <dd  >{{$colaborador->nombre}}</dd>
              <dt>Cédula</dt>
                <dd >{{$colaborador->cedula}}</dd>
              <dt>Correo</dt>
                <dd >{{$colaborador->email}}</dd> 
            </dl>
          </div>
          <div class="col-sm-4">
            <dl>
              <dt>Zona</dt>
                <dd >{{$colaborador->zona->zona}}</dd>
              <dt>Departamento/Gerencia</dt>
                <dd >{{$colaborador->area->area}}</dd> 
              <dt>Cargo</dt>
                <dd >{{$colaborador->cargo->cargo}}</dd> 
            </dl>
          </div>
          <div class="col-sm-4">
            <dl>
              <dt>Fecha de ingreso</dt>
                <dd >{{date('d/m/Y', strtotime($colaborador->fecha_ingreso))}}</dd>
            </dl>
          </div>
        </div>
        <table class="table table-bordered table-hover table-striped" id="tabla" width="100%" >
          <thead style="">
            <tr>
              <th>Categorías</th>
              <th>Items a evaluar</th>
              <th>Peso</th>
              <th>Cumplimiento</th>
              <th>Observaciones</th>
            </tr>
          </thead>
          <tbody>
            @if ($colaborador->items()->wherehas('categoria', function($q) use ($periodo) {$q->where('periodo_id', $periodo->id);})->exists())
              @foreach($colaborador->items as $item)
                @if ($item->categoria->periodo_id == $periodo->id)
                <tr>
                    {!! Form::hidden('ids[]', $item->pivot->id) !!}
                  <td>
                    {{$item->categoria->nombre}}
                  </td>
                  <td>
                    <dl class="dl-horizontal">
                      <dt>Item</dt>
                      <dd>{{$item->nombre}}</dd>
                      <dt>Indicador</dt>
                      <dd>{{$item->pivot->indicador}}</dd>
                    </dl>
                  </td>
                  <td>
                    {{$item->pivot->porcentaje}}
                  </td>
                  <td>
                    {{$item->pivot->resultado}}
                  </td>
                  <td>
                    {{$item->pivot->observaciones}}
                  </td>
                </tr>
                @endif
              @endforeach            
            @endif
          </tbody>
        </table>            
      </div>  
      <div class="box-footer with-border">
          <a href="{{route('trabajadores.show',$colaborador->id)}}" class="btn btn-default btn-flat">Cancelar</a>
          <input id="guardar" type="submit" value="Guardar" class='btn btn-success btn-flat pull-right' onclick="return confirm('¿Está seguro que quiere cerrar esta evaluación? Nota: NO SE PODRÁ MODIFICAR');" >        
      </div>       
        {!! Form::close() !!}
    </div> 
  </div>  
</div>
  
  
@endsection

@section('js')

@endsection

resources/views/dashboard/evaluaciones/anual/evaluacion.blade.php
@extends('layouts.main')

@section('title', 'Evaluación|'.$period.'|'.$colaborador->nombre)

@section('css')

@endsection

@section('titulo_modulo', 'Evaluación|'.$period.'|'.$colaborador->nombre)

@section('contenido')
<div class="row">
  <div class=" col-md-12">
      <div class=" box box-success ">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario para Evaluaciones</h3>
    </div>
    <div class="box-body" >
      @if (isset($periodo) && $periodo->condicion=='Quinto Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        {!! Form::open(['method' => 'PUT','route' => ['lideres.evaluar', $colaborador->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!}
      @elseif(isset($periodo) && $periodo->condicion=='Sexto Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        {!! Form::open(['method' => 'PUT','route' => ['administracion.evaluar', $colaborador->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!}      
      @endif   

      <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
      {!! Form::hidden('area_id', $colaborador->area_id, ['id' => 'area_id']) !!}

      <div class="row col-md-12">
        <div class="col-sm-4">
          <dl>
            <dt>Nombre</dt>
              <dd  >{{$colaborador->nombre}}</dd>
            <dt>Cédula</dt>
              <dd >{{$colaborador->cedula}}</dd>
            <dt>Correo</dt>
              <dd >{{$colaborador->email}}</dd> 
          </dl>
        </div>
        <div class="col-sm-4">
          <dl>
            <dt>Zona</dt>
              <dd >{{$colaborador->zona->zona}}</dd>
            <dt>Departamento/Gerencia</dt>
              <dd >{{$colaborador->area->area}}</dd> 
            <dt>Cargo</dt>
              <dd >{{$colaborador->cargo->cargo}}</dd> 
          </dl>
        </div>
        <div class="col-sm-4">
          <dl>
            <dt>Fecha de ingreso</dt>
              <dd >{{date('d/m/Y', strtotime($colaborador->fecha_ingreso))}}</dd>
          </dl>
        </div>
      </div>
      <table class="table table-bordered table-hover table-striped" id="tabla" width="100%" >
        <thead style="">
          <tr>
            <th width='40%'>Items a evaluar</th>
            <th width='10px'>Cumplimiento</th>
            <th>Observaciones</th>
          </tr>
        </thead>
        <tbody>
          @if ($colaborador->items()->wherehas('categoria', function($q) use ($periodo) {$q->where('periodo_id', $periodo->id);})->exists())
            @foreach($colaborador->items as $item)
              @if ($item->categoria->periodo_id == $periodo->id && $item->pivot->mes == $periodo->mes1)
              <tr>
                  {!! Form::hidden('ids[]', $item->pivot->id) !!}
                <td>
                  <dl class="dl-horizontal">
                    <dt>Categoría</dt>
                    <dd>{{$item->categoria->nombre}}</dd>
                    <dt>Item</dt>
                    <dd>{{$item->nombre}}</dd>
                    <dt>Peso</dt>
                    <dd>{{$item->pivot->porcentaje}}</dd>
                    <dt>Indicador</dt>
                    <dd><p>{{$item->indicador}}</p></dd>
                  </dl>
                </td>
                <td>
                  {!! Form::number('resultado[]', (isset($item->pivot->resultado)?$item->pivot->resultado:null), ['id' => 'resultado[]','class' => 'form-control','min'=>0, 'max'=>100, 'onkeypress'=>'return soloNumeros(event)']) !!}
                </td>
                <td>
                  {!! Form::textarea('observaciones[]', (isset($item->pivot->observaciones)?$item->pivot->observaciones:null), ['id' => 'observaciones[]','class' => 'form-control', 'placeholder'=>'Observación', 'rows'=>1]) !!}
                </td>
              </tr>
              @endif
            @endforeach            
          @endif
        </tbody>
      </table>            
    </div>  
    <div class="box-footer with-border">
      @if (isset($periodo) && $periodo->condicion=='Quinto Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        <a href="{{route('lideres.show',$colaborador->id)}}" class="btn btn-default btn-flat">Cancelar</a>
        {!! Form::submit('Guardar', ['id' => 'guardar', 'class' => 'btn btn-success btn-flat pull-right']) !!}  
      @elseif(isset($periodo) && $periodo->condicion=='Sexto Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        <a href="{{route('trabajadores.show',$colaborador->id)}}" class="btn btn-default btn-flat">Cancelar</a>
        {!! Form::submit('Guardar', ['id' => 'guardar', 'class' => 'btn btn-success btn-flat pull-right']) !!}    
      @endif            
    </div>       
      {!! Form::close() !!}
  </div> 
  </div>
  
</div>
  
  
@endsection

@section('js')
<script type="text/javascript">
  function soloNumeros(e){
      key = e.keyCode || e.which;
      tecla = String.fromCharCode(key).toLowerCase();
      letras = "1234567890";
      especiales = "8-37-39-46";

      tecla_especial = false
      for(var i in especiales){
        if(key == especiales[i]){
          tecla_especial = true;
          break;
        }
      }

      if(letras.indexOf(tecla)==-1 && !tecla_especial){
        return false;
      }
    }
</script>


@endsection

resources/views/dashboard/evaluaciones/anual/inicio.blade.php
@extends('layouts.main')

@section('title', 'Evaluación|'.$period.'|'.$colaborador->nombre)

@section('css')

@endsection

@section('titulo_modulo', 'Evaluación|'.$period.'|'.$colaborador->nombre)

@section('contenido')
<div class="row">
  <div class=" col-md-12">
      <div class=" box box-success ">
    <div class="box-header with-border">
        <h3 class="box-title">Formulario para Evaluaciones</h3>
    </div>
    <div class="box-body" >
      @if (isset($periodo) && $periodo->condicion=='Tercer Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        {!! Form::open(['method' => 'PUT','route' => ['lideres.inicio', $colaborador->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!}
      @elseif(isset($periodo) && $periodo->condicion=='Cuarto Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        {!! Form::open(['method' => 'PUT','route' => ['administracion.inicio', $colaborador->id] ,'class' => 'form-horizontal', 'files' => true,'enctype'=>"multipart/form-data"]) !!}      
      @endif   

        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
        {!! Form::hidden('area_id', $colaborador->area_id, ['id' => 'area_id']) !!}
        {!! Form::hidden('evaluacion', $periodo->id) !!}

        <div class="row">
          <div class="col-sm-4">
            <dl>
              <dt>Nombre</dt>
                <dd  >{{$colaborador->nombre}}</dd>
              <dt>Cédula</dt>
                <dd >{{$colaborador->cedula}}</dd>
              <dt>Correo</dt>
                <dd >{{$colaborador->email}}</dd> 
            </dl>
          </div>
          <div class="col-sm-4">
            <dl>
              <dt>Zona</dt>
                <dd >{{$colaborador->zona->zona}}</dd>
              <dt>Departamento/Gerencia</dt>
                <dd >{{$colaborador->area->area}}</dd> 
              <dt>Cargo</dt>
                <dd >{{$colaborador->cargo->cargo}}</dd> 
            </dl>
          </div>
          <div class="col-sm-4">
            <dl>
              <dt>Fecha de ingreso</dt>
                <dd >{{date('d/m/Y', strtotime($colaborador->fecha_ingreso))}}</dd>
            </dl>
          </div>
        </div>
        <div class="col-md-12">
          {!! Form::label('total', 'Porcentaje Total:') !!}
          <br />
          <div class="progress active">
            <div id="mes1" class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" >                  
            </div>
          </div>
        </div>
        <table class="table table-bordered table-hover table-striped" id="tabla" width="100%" >
          <thead style="">
            <tr>
              <th width="25%">Categorías</th>
              <th>Items</th>
              <th width="40%">Indicador</th>
              <th width="100px">Peso</th>
              <th width="25px">
                <a class="btn btn-success btn-xs btn-flat" id="add1" title="Añadir fila"><i class="fa fa-plus"></i> </a> 
              </th>
            </tr>
          </thead>
          <tbody>
            @if ($colaborador->items()->wherehas('categoria', function($q) use ($periodo) {$q->where('periodo_id', $periodo->id);})->exists())
              @foreach($colaborador->items as $item)
                @if ($item->categoria->periodo_id == $periodo->id)
                <tr>
                  {!! Form::hidden('ids[]', $item->pivot->id) !!}
                  <td>
                    {!! Form::select('cat[]', $categorias, $item->categoria->id, ['class' => 'form-control categoria', 'onchange'=>"categoria(this);", 'required' => 'required', 'placeholder'=>'Categoría']) !!}
                  </td> 
                  <td>
                    {!! Form::select('it[]', $items, $item->id, ['class' => 'form-control item', 'onchange'=>"item_opciones(this);", 'required' => 'required', 'placeholder'=>'Item']) !!}
                  </td>
                  <td>
                    {!! Form::textarea('indi[]', $item->indicador, ['class' => 'form-control indicador', 'required' => 'required', 'placeholder'=>'Indicador', 'rows'=>1, 'disabled'=>true]) !!}
                  </td>
                  <td>
                    <input type='text' name='por[]' id='por[]' class='form-control mes1 columnas new' min='1' max='100' required='true' onkeypress='return soloNumeros(event)' value="{{$item->pivot->porcentaje}}" placeholder='Peso'>
                  </td>  
                  <td>
                    <a class='btn btn-danger btn-xs btn-flat del' id="del[]" title='Eliminar fila'><i class='fa fa-minus'></i></a> 
                  </td> 
                </tr>
                @endif
              @endforeach
            @else
              <tr>
                  <td>
                    {!! Form::select('categoria[]', $categorias, null, [ 'class' => 'form-control categoria', 'onchange'=>"categoria(this);", 'required' => 'required', 'placeholder'=>'Seleccione']) !!}
                  </td> 
                  <td>
                    {!! Form::select('item[]',[], null, [ 'class' => 'form-control item', 'onchange'=>"item_opciones(this);", 'required' => 'required', 'placeholder'=>'Seleccione']) !!}
                  </td>
                  <td>
                    {!! Form::textarea('indicador[]', null, ['class' => 'form-control indicador', 'required' => 'required', 'placeholder'=>'Indicador', 'rows'=>1, 'disabled'=>true]) !!}
                  </td>
                  <td>
                    <input type='text' name='porcentaje[]' id='porcentaje[]' class='form-control mes1 columnas  new' min='1' max='100' required='true' onkeypress='return soloNumeros(event)' placeholder="Peso">
                  </td>  
                  <td>
                     
                  </td> 
              </tr>             
            @endif
          </tbody>
        </table>
        <div class="col-sm-offset-6">
          <span class="text-danger">No podra guardar si el total de porcentajes menor o mayor de 100% en cada mes</span>
        </div>              
    </div>  
    <div class="box-footer with-border">
      @if (isset($periodo) && $periodo->condicion=='Tercer Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        <a href="{{route('lideres.show',$colaborador->id)}}" class="btn btn-default btn-flat">Cancelar</a>
        {!! Form::submit('Guardar', ['id' => 'guardar', 'class' => 'btn btn-success btn-flat pull-right', 'disabled'=>'true']) !!}  
      @elseif(isset($periodo) && $periodo->condicion=='Cuarto Corte' && $colaborador->roles()->where('rol','colaborador')->exists())
        <a href="{{route('trabajadores.show',$colaborador->id)}}" class="btn btn-default btn-flat">Cancelar</a>
        {!! Form::submit('Guardar', ['id' => 'guardar', 'class' => 'btn btn-success btn-flat pull-right', 'disabled'=>'true']) !!}    
      @endif            
    </div>       
      {!! Form::close() !!}
  </div> 
  </div>
  
</div>
  
  
@endsection

@section('js')

<script type="text/javascript">
  /**
   * Funcion para añadir una nueva fila en la tabla
   */
  $("#add1").click(function(){
    var nuevaFila='<tr>'+
      '<td>'+
      '{!! Form::select('categoria[]', $categorias, null, [ 'class' => 'form-control categoria', 'onchange'=>"categoria(this);", 'required' => 'required', 'placeholder'=>'Seleccione']) !!}'+
      '</td>'+
      '<td>'+
      '{!! Form::select('item[]', [], null, [ 'class' => 'form-control item', 'onchange'=>"item_opciones(this);", 'required' => 'required', 'placeholder'=>'Seleccione']) !!}'+
      '</td>'+
      '<td>'+
      '{!! Form::textarea('indicador[]', null, ['class' => 'form-control indicador', 'required' => 'required', 'placeholder'=>'Indicador', 'rows'=>1, 'disabled'=>true]) !!}'+
      '</td>'+
      '<td>'+
      "<input type='text' name='porcentaje[]' id='porcentaje[]' class='form-control mes1 columnas new' min='1' max='100' required='true' onkeypress='return soloNumeros(event)' placeholder='Peso'>"+
      '</td>'+
      '<td><a class="btn btn-danger btn-xs btn-flat del" title="Eliminar fila"><i class="fa fa-minus"></i></a></td> '+
    '</tr>';
    $("#tabla tbody").append(nuevaFila);
    $('.new').keyup(function() {
      Calculate();
    });
  });

</script>
<script src="{{asset('public/js/inicio_evaluacion.js')}}"></script>

@endsection